const NANOIDLENGTH=8;
const PLAYERWAITTIME=10000;
const GAMEEXPIRYTIME=900;
const APPNAME="CodeClarity";
const APPURL="http://localhost:8080"
const VERIFICATIONTOKENEXPIRYTIME=600

export { NANOIDLENGTH, PLAYERWAITTIME ,GAMEEXPIRYTIME,APPNAME, APPURL, VERIFICATIONTOKENEXPIRYTIME
};
